// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	_xtest "example_test"
	"internal/coverage/cfile"
	"os"
	"testing"
	"testing/internal/testdeps"

	"github.com/goccy/tobari"
)

//go:linkname CoverProfileMap github.com/goccy/tobari.CoverProfileMap
func CoverProfileMap(mode string) map[string]string

var tests = []testing.InternalTest{
	{"TestExample", func(t *testing.T) { tobari.CoverWithName("TestExample", func() { _xtest.TestExample(t) }) }},
}

var benchmarks = []testing.InternalBenchmark{}
var fuzzTargets = []testing.InternalFuzzTarget{}
var examples = []testing.InternalExample{}

func init() {

	testdeps.CoverMode = "set"
	testdeps.Covered = " in example/foo"
	testdeps.CoverSelectedPackages = []string{"example/foo"}
	testdeps.CoverSnapshotFunc = cfile.Snapshot
	testdeps.CoverProcessTestDirFunc = cfile.ProcessCoverTestDir
	testdeps.CoverMarkProfileEmittedFunc = cfile.MarkProfileEmitted

	testdeps.ImportPath = "example"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	st := m.Run()
	for k, v := range CoverProfileMap("set") {
		println(k, v)
	}
	os.Exit(st)
}
