// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	_xtest "example_test"
	"internal/coverage/cfile"
	"os"
	"testing"
	"testing/internal/testdeps"
)

var tests = []testing.InternalTest{
	{"TestFoo", _xtest.TestFoo},
	{"TestBar", _xtest.TestBar},
	{"TestBaz", _xtest.TestBaz},
}

var benchmarks = []testing.InternalBenchmark{}
var fuzzTargets = []testing.InternalFuzzTarget{}
var examples = []testing.InternalExample{}

func init() {

	testdeps.CoverMode = "set"
	testdeps.Covered = " in example/foo"
	testdeps.CoverSelectedPackages = []string{"example/foo"}
	testdeps.CoverSnapshotFunc = cfile.Snapshot
	testdeps.CoverProcessTestDirFunc = cfile.ProcessCoverTestDir
	testdeps.CoverMarkProfileEmittedFunc = cfile.MarkProfileEmitted

	testdeps.ImportPath = "example"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())
}