package tool

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"golang.org/x/mod/modfile"

	"github.com/goccy/tobari/internal/version"
)

func buildPackages(ver *version.Version, lang string) (map[string]string, error) {
	if err := createApp(ver, lang); err != nil {
		return nil, fmt.Errorf("failed to create temp app: %w", err)
	}
	path := appPath(ver)
	pkgs := make(map[string]string)
	envs := os.Environ()
	newEnvs := make([]string, 0, len(envs))
	for _, kv := range envs {
		i := strings.IndexByte(kv, '=')
		key := kv[:i]
		if key == "GOFLAGS" {
			continue
		}
		newEnvs = append(newEnvs, kv)
	}
	// Get the current tobari binary path for -toolexec
	tobariPath, err := os.Executable()
	if err != nil {
		tobariPath = ""
	}

	for _, def := range []struct {
		name string
		pkg  string
	}{
		{name: "tobari.pkg", pkg: "github.com/goccy/tobari"},
		{name: "internal_tobari.pkg", pkg: "github.com/goccy/tobari/internal/tobari"},
	} {
		// Build with -toolexec to ensure consistent fingerprints with modified runtime
		// Set TOBARI_BUILD_SELF=1 to prevent recursion
		var cmd *exec.Cmd
		if tobariPath != "" {
			cmd = exec.Command("go", "build", "-o", def.name, "-buildmode=archive", "-toolexec="+tobariPath, def.pkg)
		} else {
			cmd = exec.Command("go", "build", "-o", def.name, "-buildmode=archive", def.pkg)
		}
		cmd.Dir = path
		cmd.Env = append(newEnvs, "TOBARI_BUILD_SELF=1")
		out, err := cmd.CombinedOutput()
		if err != nil {
			return nil, fmt.Errorf("failed to build app %s: %w", string(out), err)
		}
		pkgs[def.pkg] = filepath.Join(path, def.name)
	}
	return pkgs, nil
}

func createApp(ver *version.Version, lang string) error {
	path := appPath(ver)
	if err := os.MkdirAll(path, 0o755); err != nil {
		return fmt.Errorf("failed to create %s: %w", path, err)
	}
	if err := createGoMod(filepath.Join(path, "go.mod"), ver, lang); err != nil {
		return err
	}
	if err := createMain(filepath.Join(path, "main.go")); err != nil {
		return err
	}
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = path
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to run 'go mod tidy' for app %s: %s: %w", path, string(out), err)
	}
	return nil
}

func createGoMod(path string, ver *version.Version, lang string) error {
	f := new(modfile.File)
	if err := f.AddModuleStmt("tobari"); err != nil {
		return fmt.Errorf("failed to add module stmt: %w", err)
	}
	// Always set go version to match the current running Go version
	// This ensures consistency when building with toolchain directive
	goVer := lang
	if goVer == "" {
		// Use GOVERSION from environment when lang is not specified
		// This handles the case where toolchain directive switches Go versions
		goVer = getGoVersion()
	}
	goVer = strings.TrimPrefix(goVer, "go")
	if err := f.AddGoStmt(goVer); err != nil {
		return fmt.Errorf("failed to add go stmt: %w", err)
	}
	if ver.LocalPath != "" {
		rel, err := filepath.Rel(path, ver.LocalPath)
		if err != nil {
			return fmt.Errorf("failed to create relative path from %s: %w", path, err)
		}
		if err := f.AddReplace("github.com/goccy/tobari", "", rel, ""); err != nil {
			return fmt.Errorf("failed to add replace directive: %w", err)
		}
	} else {
		if err := f.AddRequire("github.com/goccy/tobari", ver.Ver); err != nil {
			return fmt.Errorf("failed to add require directive: %w", err)
		}
	}
	data, err := f.Format()
	if err != nil {
		return fmt.Errorf("failed to format go.mod: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("failed to write go.mod to %s: %w", path, err)
	}
	return nil
}

func createMain(path string) error {
	content := `
// Code generated by tobari. DO NOT EDIT!
package main

import (
	"github.com/goccy/tobari"
	_ "unsafe"
)

//go:linkname SetGIDFunc github.com/goccy/tobari/internal/tobari.SetGIDFunc
func SetGIDFunc(func() uint64)

//go:linkname AddCoverMeta github.com/goccy/tobari/internal/tobari.AddCoverMeta
func AddCoverMeta(string, []byte, []int)

//go:linkname Trace github.com/goccy/tobari/internal/tobari.Trace
func Trace(uint64, uint64, int)

func main() {
	var _ = tobari.CoverWithName
	var _ = tobari.CoverProfileMap
	var _ = tobari.Cover
	var _ = tobari.ClearCounters
	var _ = tobari.DisableCoverageCounting
	var _ = tobari.EnableCoverageCounting
	var _ = tobari.WriteAllCoverProfile
	var _ = tobari.WriteCoverProfile
	var _ = tobari.WriteCoverProfileByName

	var _ = SetGIDFunc
	var _ = AddCoverMeta
	var _ = Trace
}
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("failed to write main.go to %s: %w", path, err)
	}
	return nil
}

func appPath(ver *version.Version) string {
	return filepath.Join(
		tobariRoot(),
		getGoVersion(),
		runtime.GOARCH,
		ver.ID(),
		fmt.Sprint(os.Getpid()),
	)
}

// getGoVersion returns the current Go version from `go env GOVERSION`
// This handles the case where a toolchain directive switches Go versions
func getGoVersion() string {
	out, err := exec.Command("go", "env", "GOVERSION").Output()
	if err != nil {
		// Fallback to runtime.Version() if go env fails
		return runtime.Version()
	}
	return strings.TrimSpace(string(out))
}
