package tool

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"golang.org/x/mod/modfile"

	"github.com/goccy/tobari/internal/utils"
	"github.com/goccy/tobari/internal/version"
)

func buildPackages(ver *version.Version, lang string) (map[string]string, error) {
	appDir := appPath(ver)
	// Skip createApp if the directory was already prepared by a prior toolexec
	// invocation within the same build (compile and link share the same PPID).
	if _, err := os.Stat(filepath.Join(appDir, "go.sum")); err != nil {
		if err := createApp(ver, lang); err != nil {
			return nil, fmt.Errorf("failed to create temp app: %w", err)
		}
	}
	tobariPath, err := os.Executable()
	if err != nil {
		return nil, fmt.Errorf("failed to get tobari binary path: %w", err)
	}

	// Use go list -deps -export with -toolexec=tobari to compile and get export paths
	// for github.com/goccy/tobari and all its transitive dependencies.
	//
	// The temp app's go.mod ensures the correct version of tobari is resolved:
	//   - Released version: require github.com/goccy/tobari <version>
	//   - Development:      replace github.com/goccy/tobari => <local path>
	//
	// Using Go's build cache paths directly (instead of building separate archives)
	// guarantees that compile and link steps always reference the same package files,
	// preventing fingerprint mismatches when Go's build cache replays cached results.
	pkgs, err := utils.GoListDepsExport(appDir, tobariPath, "github.com/goccy/tobari")
	if err != nil {
		return nil, fmt.Errorf("failed to get tobari packages: %w", err)
	}
	return pkgs, nil
}

func createApp(ver *version.Version, lang string) error {
	path := appPath(ver)
	if err := os.MkdirAll(path, 0o755); err != nil {
		return fmt.Errorf("failed to create %s: %w", path, err)
	}
	if err := createGoMod(filepath.Join(path, "go.mod"), ver, lang); err != nil {
		return err
	}
	if err := createMain(filepath.Join(path, "main.go")); err != nil {
		return err
	}
	if err := utils.GoModTidy(path); err != nil {
		return err
	}
	return nil
}

func createGoMod(path string, ver *version.Version, lang string) error {
	f := new(modfile.File)
	if err := f.AddModuleStmt("tobari"); err != nil {
		return fmt.Errorf("failed to add module stmt: %w", err)
	}
	goVer := lang
	if goVer == "" {
		v, err := utils.GoVersion()
		if err != nil {
			v = runtime.Version()
		}
		goVer = v
	}
	goVer = strings.TrimPrefix(goVer, "go")
	if err := f.AddGoStmt(goVer); err != nil {
		return fmt.Errorf("failed to add go stmt: %w", err)
	}
	if ver.LocalPath != "" {
		rel, err := filepath.Rel(path, ver.LocalPath)
		if err != nil {
			return fmt.Errorf("failed to create relative path from %s: %w", path, err)
		}
		if err := f.AddReplace("github.com/goccy/tobari", "", rel, ""); err != nil {
			return fmt.Errorf("failed to add replace directive: %w", err)
		}
	} else {
		if err := f.AddRequire("github.com/goccy/tobari", ver.Ver); err != nil {
			return fmt.Errorf("failed to add require directive: %w", err)
		}
	}
	data, err := f.Format()
	if err != nil {
		return fmt.Errorf("failed to format go.mod: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("failed to write go.mod to %s: %w", path, err)
	}
	return nil
}

func createMain(path string) error {
	content := `
// Code generated by tobari. DO NOT EDIT!
package main
import _ "github.com/goccy/tobari"
func main() {}
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("failed to write main.go to %s: %w", path, err)
	}
	return nil
}

func appPath(ver *version.Version) string {
	return utils.AppPath()
}
