package tool

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"golang.org/x/mod/modfile"

	"github.com/goccy/tobari/internal/utils"
	"github.com/goccy/tobari/internal/version"
)

func buildPackages(ver *version.Version, lang string) (map[string]string, error) {
	if err := createApp(ver, lang); err != nil {
		return nil, fmt.Errorf("failed to create temp app: %w", err)
	}
	path := appPath(ver)
	pkgs := make(map[string]string)
	tobariPath, err := os.Executable()
	if err != nil {
		return nil, fmt.Errorf("failed to get tobari binary path: %w", err)
	}

	tobariPkgs := []struct {
		name string
		pkg  string
	}{
		{name: "tobari.pkg", pkg: "github.com/goccy/tobari"},
		{name: "internal_tobari.pkg", pkg: "github.com/goccy/tobari/internal/tobari"},
	}

	for _, def := range tobariPkgs {
		// Build with -toolexec to ensure consistent fingerprints with modified runtime.
		// Recursion is prevented because tobari packages are already in importcfg when building them.
		if err := utils.GoBuild(path, "-o", def.name, "-buildmode=archive", "-toolexec="+tobariPath, def.pkg); err != nil {
			return nil, err
		}
		pkgs[def.pkg] = filepath.Join(path, def.name)
	}

	// Write preliminary tobari_pkg.json so that sub-invocations of tobari
	// (from the go list below) can find the built archives without recursion.
	if err := writeTobariPkgs(pkgs); err != nil {
		return nil, err
	}

	// Collect all transitive dependencies with their export paths.
	// This ensures packages like archive/tar (needed by tobari_archive.go)
	// are available in the link importcfg even if the user's code doesn't use them.
	deps, err := utils.GoListDepsExport(path, tobariPath, "github.com/goccy/tobari")
	if err != nil {
		return nil, fmt.Errorf("failed to get tobari deps: %w", err)
	}
	for pkg, exportPath := range deps {
		if _, ok := pkgs[pkg]; !ok {
			pkgs[pkg] = exportPath
		}
	}

	return pkgs, nil
}

func createApp(ver *version.Version, lang string) error {
	path := appPath(ver)
	if err := os.MkdirAll(path, 0o755); err != nil {
		return fmt.Errorf("failed to create %s: %w", path, err)
	}
	if err := createGoMod(filepath.Join(path, "go.mod"), ver, lang); err != nil {
		return err
	}
	if err := createMain(filepath.Join(path, "main.go")); err != nil {
		return err
	}
	if err := utils.GoModTidy(path); err != nil {
		return err
	}
	return nil
}

func createGoMod(path string, ver *version.Version, lang string) error {
	f := new(modfile.File)
	if err := f.AddModuleStmt("tobari"); err != nil {
		return fmt.Errorf("failed to add module stmt: %w", err)
	}
	goVer := lang
	if goVer == "" {
		v, err := utils.GoVersion()
		if err != nil {
			v = runtime.Version()
		}
		goVer = v
	}
	goVer = strings.TrimPrefix(goVer, "go")
	if err := f.AddGoStmt(goVer); err != nil {
		return fmt.Errorf("failed to add go stmt: %w", err)
	}
	if ver.LocalPath != "" {
		rel, err := filepath.Rel(path, ver.LocalPath)
		if err != nil {
			return fmt.Errorf("failed to create relative path from %s: %w", path, err)
		}
		if err := f.AddReplace("github.com/goccy/tobari", "", rel, ""); err != nil {
			return fmt.Errorf("failed to add replace directive: %w", err)
		}
	} else {
		if err := f.AddRequire("github.com/goccy/tobari", ver.Ver); err != nil {
			return fmt.Errorf("failed to add require directive: %w", err)
		}
	}
	data, err := f.Format()
	if err != nil {
		return fmt.Errorf("failed to format go.mod: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("failed to write go.mod to %s: %w", path, err)
	}
	return nil
}

func createMain(path string) error {
	content := `
// Code generated by tobari. DO NOT EDIT!
package main
import _ "github.com/goccy/tobari"
func main() {}
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("failed to write main.go to %s: %w", path, err)
	}
	return nil
}

func appPath(ver *version.Version) string {
	return utils.AppPath()
}
